version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: tickets_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1523
      - POSTGRES_DB=sistema_tickets
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  api:
    build: .
    container_name: tickets_api
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
    depends_on:
      - db

volumes:
  postgres_data: